### ISSUE TITLE
Smooth Locomotion can't rotate using the right stick

### ISSUE THREAD

**Issue by flowerbearttv** [TheNexusAvenger/Nexus-VR-Character-Model#11] opened 2022-07-06 12:53 UTC
Valve Index Headset and controllers, Using the [Nexus VR Character Model Demo place](https://www.roblox.com/games/1502435445/Nexus-VR-Character-Model-Demo)

Tap/Smooth rotation was already confirmed to work in issue #5 so I know that I have to use the right stick to rotate

However, when attempting to use the right stick to rotate in Smooth Locomotion, nothing happens, however, in teleport mode, rotation on the right stick works as expected.

**Comment by TheNexusAvenger** [comment] 2022-07-06 12:59
This functionality is currently in the [`SmoothLocomotionController`](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/SmoothLocomotionController.lua#L82) but not the [`TeleportController`](https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/TeleportController.lua). It isn't exactly a bug since it is functioning as intended, but the intended design isn't what you would expect.

**Comment by TheNexusAvenger** [comment] 2022-07-20 14:11
I take back what I said about it being a missing feature - it is a bug for a feature I forgot even existed. Pull request #13 should address this by using the known-good code in the teleport controller. Once the pull request is merged and the update goes up, I'll close the issue.

**Closed as completed** 2022-07-21 00:15 UTC
Labels: bug
