### ISSUE TITLE
[Quest 2] having to turn my joysticks in all sorts of directions to move properly, Third person inversion?

### ISSUE THREAD

**Issue by GarrySwepman** [TheNexusAvenger/Nexus-VR-Character-Model#47] opened 2024-11-13 09:55 UTC
VR HEADSET: Quest 2
Play method: Meta Air Link To Windows 10 PC
Controllers: Stock
Issue: The direction I turn my left control joystick initially functions as intended but after moving around it seems to get confused and the control stick completely turns me in various directions, in some cases I have had put my joystick right or left to go forward so it's not just inverted, and I half tried playing several different games with nexus support and the issue persists, I have also tried recentering in the nexus vr menu and it does not fix the issue, I did however find something interesting, by going into third person using the nexus menu my third person perspective is inverted to whatever the opposite direction of where it roughly should be and I think this is related to the issue.
![metascreenshotroblox1](https://github.com/user-attachments/assets/57405033-e4b2-4246-9ff8-572c5d1cfc98)

**Comment by TheNexusAvenger** [comment] 2024-11-13 14:03
Duplicate of #45

**Closed as completed by TheNexusAvenger** 2024-11-13 14:03 UTC
Labels: bug, duplicate, wontfix, roblox-problem

**Comment by GarrySwepman** [comment] 2024-11-13 22:13
Oh I see, Thank you.
