### ISSUE TITLE
Constant Black screens and camera messed up.

### ISSUE THREAD

**Issue by watameln** [TheNexusAvenger/Nexus-VR-Character-Model#20] opened 2023-02-12 22:00 UTC
All games that have this is experiencing this... Your camera will tilt to the sides if you look left and right. Your vision will be black most of the time when looking straight and crap. its very broken atm

**Comment by TheNexusAvenger** [comment] 2023-02-12 22:08
Duplicate of #19

**Closed as completed by TheNexusAvenger** 2023-02-12 22:08 UTC
Labels: bug
